# Modul 1

In [2]:
# Setting up workplace
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

## Q1

In [ ]:
# Pandas version
pd.__version__ #2.3.1

'2.3.1'

In [4]:
# Reading the dataset as pandas dataframe
# There are many ways to read data into pandas dataframe, for example from excel, json, sql etc. Each of them has its own function in pandas library.

df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

## Q2 - 9704

In [5]:
# Exploratory Data Analysis (EDA)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   engine_displacement  9704 non-null   int64
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64
 6   origin               9704 non-null   object
 7   fuel_type            9704 non-null   object
 8   drivetrain           9704 non-null   object
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB

In [9]:
# Exploratory Data Analysis (EDA)
pd.set_option("display.precision", 2) # setting precision to 2 decimal points without changing the actual data
df.describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,9704.00,9222.00,8996.00,9704.00,8774.00,9704.00,9.20e+03,9704.00
mean,199.71,3.96,149.66,3001.28,15.02,2011.48,-6.41e-03,14.99
std,49.46,2.00,29.88,497.89,2.51,6.66,1.05e+00,2.56
min,10.00,0.00,37.00,952.68,6.00,2000.00,-4.00e+00,6.20
25%,170.00,3.00,130.00,2666.25,13.30,2006.00,-1.00e+00,13.27
50%,200.00,4.00,149.00,2993.23,15.00,2012.00,0.00e+00,15.01
75%,230.00,5.00,170.00,3334.96,16.70,2017.00,1.00e+00,16.71
max,380.00,13.00,271.00,4739.08,24.30,2023.00,4.00e+00,25.97

## Q3 - 2

In [8]:
# the actual unique values in 'fuel_type' column
print(df['fuel_type'].unique())

# count of uniunique values in 'fuel_type' colum
print(df['fuel_type'].nunique())

['Gasoline' 'Diesel']
2

## Q4 - 4

In [ ]:
# How to find out how many columns have missing values?
# One way is to use isnull() function along with sum() function to get the count of missing values in each column. If the count is greater than 0, then that column has missing values.
# Another way is to use info() function which shows the count of non-null values in each column. If the count is less than the total number of rows, then that column has missing values.

df.isnull().sum()
# There are 4 columns with missing values: 'horsepower', 'weight', 'acceleration', 'mpg'

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

## Q5 - 23.75

In [11]:
# Grouping and Aggregation
df.groupby('origin')['fuel_efficiency_mpg'].max()

origin
Asia      23.76
Europe    25.97
USA       24.97
Name: fuel_efficiency_mpg, dtype: float64

In [13]:
# An other way to find out the maximum fuel efficiency for Asian cars
# Accessing the rows where origin is "Asia", then acessing the 'fuel_efficiency_mpg' column and finding the maximum value
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max().round(2)

np.float64(23.76)

## Q6 - Yes, it decreased

In [ ]:
# meadian value of the horsepower column
df['horsepower'].median() 
# 149.0

np.float64(149.0)

In [ ]:
# the most frequent value of the horsepower column
# The mode() function returns a Series, which means if there are 2 modes, it will show both. To get the first element of the Series (the first mode) we can add [0] at the end.
df['horsepower'].mode()
# 152.0

np.float64(152.0)

In [17]:
# Filling missing values of he horsepower column with the most frequent value (mode)
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode())

In [ ]:
# Recalculating the median value of the horsepower column after filling missing values
df['horsepower'].median()
# 149.0

np.float64(149.0)

Everything below this line is not part of the optional homework, but rather my personal notes.

---

# Array

In [5]:
import numpy as np

In [6]:
np

In [7]:
np.zeros(5)
# np.zero() is used to create an array of given shape and type, filled with zeros.

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)
# np.ones() is used to create an array of given shape and type, filled with ones

array([1., 1., 1., 1., 1.])

In [9]:
np.full(5, 34)
# np.full() is used to create an array of given shape and type, filled with and specified value.

array([34, 34, 34, 34, 34])

In [10]:
# List in python: can contain elements of different data types
my_list = [1, 2.5, 'Hello', True]
# numpy array: elements should be raw number
my_array = np.array([1, 2.5, 3, 4])

In [11]:
# convert list to numpy array
my_list = [1, 2, 3, 4]
my_array = np.array(my_list)

In [12]:
my_array

array([1, 2, 3, 4])

In [13]:
my_list

[1, 2, 3, 4]

In [14]:
# accessing elements in numpy array
# to access elements in numpy array, we use indexing similar to lists in python
my_array[2]  # accessing the third element, index starts from 0

np.int64(3)

In [15]:
# we can also changed the value of an element by accessing it via its index
my_array[2] = 10
my_array

array([ 1,  2, 10,  4])

In [16]:
np.arange(10, 22)           
# np.arange() is used to create an array with evenly spaced values within a given interval.

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [17]:
np.linspace(0, 1, 5)
# np.linspace() is used to create an array of evenly spaced numbers over a specified interval.
# output: an array of 5 numbers evenly spaced between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Multidimentional arrays

In [18]:
np.zeros((5,2)) #5 rows, 2 columns
# np.zeros() creates multidimensional arrays when you pass a tuple as the shape argument.
# A tuple in Python is an ordered collection of items. tuples can’t be changed, they’re immutable!

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
new_array = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])

In [20]:
# accessing elements in numpy array
# to access elements in a 2D numpy array, we use row and column indices
# to access elements in a multidimensional array, we use multiple indices separated by commas.
new_array[1, 2]  # accessing element at 2nd row and 3rd column. Indices start from 0.

np.int64(6)

In [21]:
new_array[:, 1]  # accessing all rows in 2nd column
# we can use this colon operator to access all elements along a specific axis
# Accessing elements in a specific row or column can be useful when you want to modify or extract values from an array

array([2, 5, 8])

In [22]:
# generating random arrays
np.random.rand(3, 4)  # creates a 3 rows x 4 columns array with random values between 0 and 1
# useful for initializing weights in machine learning models!

array([[0.49540254, 0.09937761, 0.70507534, 0.22101175],
       [0.68090128, 0.59564576, 0.5141213 , 0.74349119],
       [0.74463279, 0.4558533 , 0.94968792, 0.21646136]])

In [23]:
# the problem is, the random values generated are different each time we run the code.
# To get the same random values each time, we must  set a random seed using np.random
np.random.seed(42)  # setting the random seed to 42
np.random.rand(3, 4)  # creates a 3 rows x 4 columns array with random values between 0 and 1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

In [24]:
# there are many kind of distributions to generate random numbers from. Here are some examples:
np.random.randn(3, 4)  # random numbers from a standard normal distribution (mean 0, stddev 1). Equivalent to np.random.normal(loc=0.0, scale=1.0, size=(3, 4))
np.random.normal(loc=0.0, scale=1.0, size=(3, 4))  # random numbers from a normal distribution with mean 0 and stddev 1, all parameters are customizable.

array([[ 1.46564877, -0.2257763 ,  0.0675282 , -1.42474819],
       [-0.54438272,  0.11092259, -1.15099358,  0.37569802],
       [-0.60063869, -0.29169375, -0.60170661,  1.85227818]])

In [25]:
np.random.randint(low=0, high= 10, size=(3, 4))  # random integers between 0 and 10

array([[6, 7, 2, 0],
       [3, 1, 7, 3],
       [1, 5, 5, 9]])

## Operations

There are element-wise operations and matrix-wise operation (linear algebra style multiplication).

Element-wise operations:

In [26]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [27]:
a + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [28]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [29]:
#comparing 
a > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [30]:
b = np.random.randint(0, 10, (3, 3))
b

array([[3, 5, 1],
       [9, 1, 9],
       [3, 7, 6]])

In [31]:
a > b # element-wise comparison

array([[False, False,  True],
       [False,  True, False],
       [ True,  True,  True]])

In [32]:
# if I want to know which elements are greater in a than in b, I can use:
a[a > b]

array([3, 5, 7, 8, 9])

In [33]:
# other functions:
a.mean()

np.float64(5.0)

In [34]:
a.min()

np.int64(1)

In [35]:
a.sum()

np.int64(45)

In [36]:
# finding the smallest element in each row
a.min(axis=1)  # axis=1 means we are operating along rows/ going across rows

array([1, 4, 7])

In [37]:
a.min(axis=0)  # axis=0 means we are operating along columns/ going down columns

array([1, 2, 3])